#pragma once

enum class ReturnCode{
   SUCCESS,
   FAILURE,
   WROND_CREDENTIALS,
   DIRECTORY_ERROR,
   DATABASE_FILE_ERROR,
   DATABASE_FILE_CORRUPT_ERROR,
   DATABASE_STORE_ERROR,
   DATABASE_STORE_CORRUPT_ERROR,
   DATABASE_NOT_FOUND,
   KEY_NOT_FOUND,
   KEY_ALREADY_EXIST,
   LOG_FILE_ERROR,
   LOG_FILE_CORRUPT_ERROR,
};